// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BigGoods: typeof import('./src/components/custom/bigGoods.vue')['default']
    BottomInfo: typeof import('./src/components/custom/bottomInfo.vue')['default']
    CartGoods: typeof import('./src/components/cart/cartGoods.vue')['default']
    Crumbs: typeof import('./src/components/custom/crumbs.vue')['default']
    DescBars: typeof import('./src/components/custom/descBars.vue')['default']
    HomeGoods: typeof import('./src/components/home/homeGoods.vue')['default']
    HomeSpecial: typeof import('./src/components/home/homeSpecial.vue')['default']
    MiniBrand: typeof import('./src/components/custom/miniBrand.vue')['default']
    MiniGoods: typeof import('./src/components/custom/miniGoods.vue')['default']
    Popup: typeof import('./src/components/custom/popup.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Swiper: typeof import('./src/components/custom/swiper.vue')['default']
    WatchShowAndHide: typeof import('./src/components/custom/watchShowAndHide.vue')['default']
  }
}
